[package]
name = "chill-rs"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]

[lib]
name = "chill"
path = "src/lib.rs"

[dependencies]
reqwest = "0.9.4"
rb = "0.3.2"
rodio = "0.8.1"
minimp3 = "0.3.0"
